[project]
name = "datasette-town"
version = "0.0.1a4"
description = "Share SQL queries"
readme = "README.md"
authors = [{name = "Alex Garcia"}]
license = "Apache-2.0"
classifiers=[
    "Framework :: Datasette"
]
requires-python = ">=3.10"
dependencies = [
    "datasette>=1.0a19",
    "datasette-plugin-router>=0.0.1a2",
    "datasette-vite>=0.0.1a4",
    "datasette-acl>=0.6a1",
    "datasette-acl-share>=0.0.1a7",
    "pydantic>=2",
    "python-ulid>=3",
    "sqlite-migrate>=0.1b0",
    "sqlite-utils>=3.38",
    "datasette-user-profiles>=0.1.0a6",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "datasette-debug-gotham",
    "datasette-sidebar>=0.0.1a3"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project.urls]
Homepage = "https://github.com/datasette/datasette-town"
Changelog = "https://github.com/datasette/datasette-town/releases"
Issues = "https://github.com/datasette/datasette-town/issues"
CI = "https://github.com/datasette/datasette-town/actions"

[project.entry-points.datasette]
town = "datasette_town"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.packages.find]
exclude = [
    "frontend",
]

[tool.setuptools.package-data]
datasette_town = ["static/**/*", "templates/*", "manifest.json"]
